# Generated by Django 3.1.4 on 2021-10-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='full_name',
            field=models.CharField(default='xD kavo', max_length=200),
            preserve_default=False,
        ),
    ]
