# Generated by Django 4.2.18 on 2025-01-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0002_people_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='full_name',
        ),
    ]
