# Generated by Django 3.2.8 on 2024-02-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0002_people_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='full_name',
        ),
    ]
